import os
os.system("clear")

os.system("echo File Recovery Script")
os.system("For Programing Wonders")
os.system("echo The list of devices is")
os.system("lsblk")
os.system("echo enter the device to be used")
devname = input("")
imgname = input("Enter the image name \n")
os.system("dd if="+devname+" of=" + imgname +" bs=512")
os.system("echo showing inode number of files")
os.system("fls "+ imgname)
inodeno = input("Enter the inode of the deleted file ")
os.system("istat "+ imgname + " " + inodeno )
os.system("echo the contents of the recovered file are")
os.system("icat "+ imgname +" "+ inodeno)
os.system("echo enter the name of the file where data to be stored with extension")
newfile = input("")
os.system("icat "+ imgname +" "+ inodeno +" > "+ newfile )
os.system("echo the contents of the file are")
os.system("cat "+ newfile )